name: roots-project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas
  - matplotlib
  - pillow
  - scikit-image
  - opencv
  - pybullet
  - pytest
  - pip:
      - tensorflow==2.15.1
      - patchify==0.2.3
      - skan==0.11.1
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - -e .
